### ISSUE TITLE
Support ETag for objects

### ISSUE THREAD

**Issue by alvarosanchez** [cameritelabs/oci-emulator#20]
It would be great if you could support ETag for objects. It could be a random value to begin with.

I'm also happy to submit a PR if you provide some guidance on where this should be added.

**Comment by ezequielramos** [comment]
Hey @alvarosanchez! I'm happy to know that someone else is using oci-emulator! 😄 

Let me see if I understood what you want. You want to add ETag information for objects on object-storage, is that right?

We already support it for buckets (we are using a random uuid value as you suggested), but we don't support it to the objects itself yet. 

I can guide you to submit a PR with this improvement. You are looking for [this file](https://github.com/cameritelabs/oci-emulator/blob/main/app/routes/object_storage/objects.py). On the `put_object` method, you can add a new information for the object like this:

```python
    bucket["_objects"].append(
        {
            "cache_control": cache_control,
            "content_type": content_type,
            "object_name": subpath,
            "ref_obj": ref_obj,
            "content_disposition": content_disposition,
            "etag": str(uuid.uuid4()), # <----- you can add a etag information like this
        }
    )
```

You should be able to return that information on `list_objects` or `get_object_route` (depending of your use case) method after that.

I don't know how/where this information is being provided on these routes though, maybe on the body itself but maybe on the response headers... You can try to debbug the SDK to understand how it works, I usually use the scripts inside the `reverse_engineering` folder to test it.

Last of all, you can add a unit test [here](https://github.com/cameritelabs/oci-emulator/blob/main/tests/test_object_storage_operations.py) checking if the etag information is different than null (I suppose we are returning null).

Let me know if I can help you with something else! 👍
